module.exports = {
    extends: ["eslint:recommended", "plugin:@typescript-eslint/recommended"],
    parser: "@typescript-eslint/parser",
    plugins: ["@typescript-eslint"],
    ignorePatterns: [
        "*.min.*",
        "*.d.ts",
        "CHANGELOG.md",
        "dist",
        "LICENSE*",
        "output",
        "out",
        "coverage",
        "public",
        "temp",
        "package-lock.json",
        "pnpm-lock.yaml",
        "yarn.lock",
        "__snapshots__",
        // ignore for in lint-staged
        "*.css",
        "*.png",
        "*.ico",
        "*.toml",
        "*.patch",
        "*.txt",
        "*.crt",
        "*.key",
        "Dockerfile",
        // force include
        "!.github",
        "!.vscode",
    ],
    rules: {
        indent: "off",
        "@typescript-eslint/indent": ["error", 4],
        "comma-dangle": "off",
        "@typescript-eslint/comma-dangle": ["error", "always-multiline"],
        semi: "off",
        "@typescript-eslint/semi": [
            "error",
            "always",
            { omitLastInOneLineBlock: true },
        ],
        "linebreak-style": ["error", "unix"],
    },
};
